name: Scheduled Python Script

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8:00 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Needed for push access

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas homeharvest # Install the libraries needed by your script

      - name: Configure Git for commits
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
      - name: Run Python script
        run: python your_script_name.py # Make sure your script file is named this
